# fly.toml app configuration file generated for ecofriends-livros on 2023-12-12T23:40:53-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ecofriends-livros"
primary_region = "gru"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_NAME = "ECOFRIENDS"
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "mysql"
  DB_HOST = "aws.connect.psdb.cloud"
  DB_PORT = "3306"
  DB_DATABASE = "ecofriends_livros_db"
  MYSQL_ATTR_SSL_CA= "/etc/ssl/certs/ca-certificates.crt"
  MAIL_MAILER = "smtp"
  MAIL_HOST = "smtp.gmail.com"
  MAIL_PORT = "587"
  MAIL_USERNAME = "livrosenem3@gmail.com"
  MAIL_ENCRYPTION = "TLS"
  MAIL_FROM_ADDRESS = "livrosenem3@gmail.com"
  MAIL_FROM_NAME = "Ecofriends"
  BROADCAST_DRIVER = "log"
  CACHE_DRIVER = "file"
  FILESYSTEM_DISK = "local"
  QUEUE_CONNECTION = "database"
  SESSION_LIFETIME = "120"
  LOG_DEPRECATIONS_CHANNEL = "null"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
#  release_command = "php artisan migrate --force"

[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:listen"